% This is PUMA3d.M, a 3D Matlab Kinematic model of a Puma robot located
% in the robotics lab of Walla Walla University.
% The file uses CAD data converted to Matlab using cad2matdemo.m, which 
% is located on the Mathworks central file exchange.
%
% This file is still being developed, for the latest version check the
% Mathworks central file exchange.
%
% Todo list:
% 1) optimize pumaANI, lots of stuff in loop that needs help.
% 2) move x, y, and z position to end effecter, not link 6 origin.
% 3) Toggle kinematics buttons on/off with inverse kinematics button.
% 4) Make this work with real time inverse kinematics.
% 5) Make the track on and off option better.
% 6) add other things that makes this program fun.
% 7) check for noplots and nogos
% 8) add some better "demos" for the button
% 9) Fix problem of more than one robot window.
%

function puma3d
% GUI kinematic demo for the Puma Robot.
% Robot geometry uses the CAD2MATDEMO code in the Mathworks file exchange
%
%%

addpath gui/

init_arm

global fig_1
%
% Create the push buttons: pos is: [left bottom width height]
demo = uicontrol(fig_1,'String','Demo','callback',@demo_button_press,...
    'Position',[20 5 60 20]);
setappdata(0, 'demo', demo);

rnd_demo= uicontrol(fig_1,'String','Random Move','callback',@rnd_demo_button_press,...
    'Position',[100 5 80 20]);
setappdata(0, 'rnd_demo', rnd_demo);

clr_trail= uicontrol(fig_1,'String','Clr Trail','callback',@clr_trail_button_press,...
    'Position',[200 5 60 20]);
setappdata(0, 'clr_trail', clr_trail);

home= uicontrol(fig_1,'String','Home','callback',@home_button_press,...
    'Position',[280 5 70 20]);
setappdata(0, 'home', home);

create_ball = uicontrol(fig_1,'String','Create Ball','callback',@create_ball_button_press,...
    'Position', [370 5 80 20]);
setappdata(0, 'create_ball', create_ball);

% 
% Kinematics Panel
%
kin_panel = {};
K_p = uipanel(fig_1,...
    'units','pixels',...
    'Position',[20 45 265 200],...
    'Title','Kinematics','FontSize',11);
kin_panel.uipanel = K_p;
kin_panel.theta = [{}, {}, {}, {}, {}, {}];
%
%     Angle    Range                Default Name
%     Theta 1: 320 (-160 to 160)    90       Waist Joint  
%     Theta 2: 220 (-110 to 110)   -90       Shoulder Joint
%     Theta 3: 270 (-135 to 135)   -90       Elbow Joint    
%     Theta 4: 532 (-266 to 266)     0       Wrist Roll
%     Theta 5: 200 (-100 to 100)     0       Wrist Bend  
%     Theta 6: 532 (-266 to 266)     0       Wrist Swivel

% offset to define the "home" position as UP.
home_pos = [90, -90, -90, 0, 0, 0];
setappdata(0, 'home_pos', home_pos);
max_pos = [-160, -110, -350, -266, -100, -266];
setappdata(0, 'max_pos', max_pos);
min_pos = [160, 110, 350, 266, 100, 266];
setappdata(0, 'min_pos', min_pos);

LD = 105; % Left, used to set the GUI.
HT = 18;  % Height
BT = 156; % Bottom

%%  GUI buttons for Theta 1.  pos is: [left bottom width height]
kin_panel.theta(1).slider= uicontrol(K_p,'style','slider',...
    'Max',160,'Min',-160,'Value',0,...
    'SliderStep',[0.05 0.2],...
    'callback',@slider_button_press,...
    'Position',[LD BT 120 HT]);
kin_panel.theta(1).min= uicontrol(K_p,'style','text',...
    'String','-160',...
    'Position',[LD-30 BT+1 25 HT-4]); % L, from bottom, W, H
kin_panel.theta(1).max= uicontrol(K_p,'style','text',...
    'String','+160',...
    'Position',[LD+125 BT+1 25 HT-4]); % L, B, W, H
kin_panel.theta(1).text= uicontrol(K_p,'style','text',...
    'String','T1',...
    'Position',[LD-100 BT 20 HT]); % L, B, W, H
% t1_text = uicontrol(K_p,'style','text',... % when matlab fixes uicontrol
%     'String','t1',...                      % for TeX, then I can use this.  
%     'Position',[LD-100 BT 20 HT]); % L, B, W, H
kin_panel.theta(1).edit= uicontrol(K_p,'style','edit',...
    'String',0,...
    'callback',@edit_button_press,...
    'Position',[LD-75 BT 30 HT]); % L, B, W, H

%
%%  GUI buttons for Theta 2.

BT= 126;   % Bottom
kin_panel.t2 = {};
kin_panel.theta(2).slider= uicontrol(K_p,'style','slider',...
    'Max',115,'Min',-115,'Value',0,...        % Mech. stop limits !
    'SliderStep',[0.05 0.2],...
    'callback',@slider_button_press,...
    'Position',[LD BT 120 HT]);
kin_panel.theta(2).min= uicontrol(K_p,'style','text',...
    'String','-110',...
    'Position',[LD-30 BT+1 25 HT-4]); % L, from bottom, W, H
kin_panel.theta(2).max= uicontrol(K_p,'style','text',...
    'String','+110',...
    'Position',[LD+125 BT+1 25 HT-4]); % L, B, W, H
kin_panel.theta(2).text= uicontrol(K_p,'style','text',...
    'String','T2',...
    'Position',[LD-100 BT 20 HT]); % L, B, W, H
kin_panel.theta(2).edit= uicontrol(K_p,'style','edit',...
    'String',0,...
    'callback',@edit_button_press,...
    'Position',[LD-75 BT 30 HT]); % L, B, W, H

%
%%  GUI buttons for Theta 3.
BT = 96;   % Bottom
kin_panel.t3 = {};
kin_panel.theta(3).slider= uicontrol(K_p,'style','slider',...
    'Max',135,'Min',-135,'Value',0,...
    'SliderStep',[0.05 0.2],...
    'callback',@slider_button_press,...
    'Position',[LD BT 120 HT]);
kin_panel.theta(3).min= uicontrol(K_p,'style','text',...
    'String','-135',...
    'Position',[LD-30 BT+1 25 HT-4]); % L, from bottom, W, H
kin_panel.theta(3).max= uicontrol(K_p,'style','text',...
    'String','+135',...
    'Position',[LD+125 BT+1 25 HT-4]); % L, B, W, H
kin_panel.theta(3).text= uicontrol(K_p,'style','text',...
    'String','T3',...
    'Position',[LD-100 BT 20 HT]); % L, B, W, H
kin_panel.theta(3).edit= uicontrol(K_p,'style','edit',...
    'String',0,...
    'callback',@edit_button_press,...
    'Position',[LD-75 BT 30 HT]); % L, B, W, H

%
%%  GUI buttons for Theta 4.
BT = 66;   % Bottom
kin_panel.t4 = {};
kin_panel.theta(4).slider= uicontrol(K_p,'style','slider',...
    'Max',266,'Min',-266,'Value',0,...
    'SliderStep',[0.05 0.2],...
    'callback',@slider_button_press,...
    'Position',[LD BT 120 HT]);
kin_panel.theta(4).min= uicontrol(K_p,'style','text',...
    'String','-266',...
    'Position',[LD-30 BT+1 25 HT-4]); % L, from bottom, W, H
kin_panel.theta(4).max= uicontrol(K_p,'style','text',...
    'String','+266',...
    'Position',[LD+125 BT+1 25 HT-4]); % L, B, W, H
kin_panel.theta(4).text= uicontrol(K_p,'style','text',...
    'String','T4',...
    'Position',[LD-100 BT 20 HT]); % L, B, W, H
kin_panel.theta(4).edit= uicontrol(K_p,'style','edit',...
    'String',0,...
    'callback',@edit_button_press,...
    'Position',[LD-75 BT 30 HT]); % L, B, W, H
%
%%  GUI buttons for Theta 5.
BT = 36;   % Bottom
kin_panel.t5 = {};
kin_panel.theta(5).slider= uicontrol(K_p,'style','slider',...
    'Max',100,'Min',-100,'Value',0,...
    'SliderStep',[0.05 0.2],...
    'callback',@slider_button_press,...
    'Position',[LD BT 120 HT]);
kin_panel.theta(5).min= uicontrol(K_p,'style','text',...
    'String','-100',...
    'Position',[LD-30 BT+1 25 HT-4]); % L, from bottom, W, H
kin_panel.theta(5).max= uicontrol(K_p,'style','text',...
    'String','+100',...
    'Position',[LD+125 BT+1 25 HT-4]); % L, B, W, H
kin_panel.theta(5).text= uicontrol(K_p,'style','text',...
    'String','T5',...
    'Position',[LD-100 BT 20 HT]); % L, B, W, H
kin_panel.theta(5).edit= uicontrol(K_p,'style','edit',...
    'String',0,...
    'callback',@edit_button_press,...
    'Position',[LD-75 BT 30 HT]); % L, B, W, H
%
%%  GUI buttons for Theta 6.
BT = 6;   % Bottom
kin_panel.t6 = {};
kin_panel.theta(6).slider= uicontrol(K_p,'style','slider',...
    'Max',266,'Min',-266,'Value',0,...
    'SliderStep',[0.05 0.2],...
    'callback',@slider_button_press,...
    'Position',[LD BT 120 HT]);
kin_panel.theta(6).min= uicontrol(K_p,'style','text',...
    'String','-266',...
    'Position',[LD-30 BT+1 25 HT-4]); % L, from bottom, W, H
kin_panel.theta(6).max= uicontrol(K_p,'style','text',...
    'String','+266',...
    'Position',[LD+125 BT+1 25 HT-4]); % L, B, W, H
kin_panel.theta(6).text= uicontrol(K_p,'style','text',...
    'String','T6',...
    'Position',[LD-100 BT 20 HT]); % L, B, W, H
kin_panel.theta(6).edit= uicontrol(K_p,'style','edit',...
    'String',0,...
    'callback',@edit_button_press,...
    'Position',[LD-75 BT 30 HT]); % L, B, W, H
%
setappdata(0, 'kin_panel', kin_panel);

% rmpath gui/
end

% Finally.